<a href="https://colab.research.google.com/github/deekshitharatna/ML-LAB-24AG5A6616/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy


NumPy is a Python library created in 2005 that performs numerical calculations. It is generally used for working with arrays.

Why Use Numpy



In Python, we use lists to work with arrays. But when it comes to large array operations, Python lists are not optimized enough.

Numpy arrays are optimized for complex mathematical and statistical operations. Operations on NumPy are up to 50x faster than iterating over native Python lists using loops.

Import NumPy in Python

In [2]:

import numpy as np

NumPy Array Creation

In [3]:
list1 = [2, 4, 6, 8]

In [4]:
# create numpy array using list1
array1 = np.array(list1)
print(array1)


[2 4 6 8]


Instead of creating a list and using the list variable with the np.array() function, we can directly pass list elements as an argument.

In [5]:
# create numpy array using a list
array1 = np.array([2, 4, 6, 8])
print(array1)

[2 4 6 8]


Create a 2-D NumPy Array

In [6]:
# create a 2D array with 2 rows and 4 columns
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array1)

[[1 2 3 4]
 [5 6 7 8]]


Create a 3-D NumPy Array

In [7]:

# create a 3D array with 2 "slices", each of 3 rows and 4 columns
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


Check Data Type of a NumPy Array

In [12]:
#create an array of integers
array1 = np.array([2, 4, 6])

In [13]:
# check the data type of array1
print(array1.dtype)

int64


Check dimensions of an Numpy Array

In [14]:
print(array1.ndim)

1



Check Size of Numpy array

In [15]:
print(array1.size)

3


NumPy Array shape Attribute

In NumPy, the shape attribute returns a tuple of integers that gives the size of the array in each dimension.

In [16]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])

In [17]:
print(array1.shape)

(2, 3)


NumPy Array itemsize Attribute

In [18]:
# create a default 1-D array of integers
array1 = np.array([6, 7, 8, 10, 13])

# create a 1-D array of 32-bit integers
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)

# use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)
print(array2.itemsize)

8
4


NumPy Array data Attribute

In [19]:
array1 = np.array([1, 3, 5, 7, 9])

# access numpy elements using index
print(array1[0])
print(array1[2])
print(array1[4])

1
5
9


Modify Array Elements Using Index

In [20]:

array1[1]=10
print(array1)

[ 1 10  5  7  9]


2-D NumPy Array Indexing

In [21]:

# create a 2D array
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])


# access the element at the second row and fourth column
element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)

# access the element at the first row and second column
element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 15
2nd Element at First Row: 3


NumPy Statistical Functions

In [22]:

# create a 1D array with 5 elements
array1 = np.array([1, 2, 3, 4, 5])

# calculate the median
median = np.median(array1)

print(median)

3.0


Compute Mean Using NumPy

In [23]:

# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the mean of marks
mean_marks = np.mean(marks)

print(mean_marks)

77.2


Standard Deviation of NumPy Array

In [24]:

# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.std(marks)
print(std_marks)

6.368673331236263


Numpy Percentile

In [25]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.percentile(marks,50)
print(std_marks)

78.0


Numpy min

In [26]:

# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.min(marks)
print(std_marks)

66



Numpy max

In [27]:

# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.max(marks)
print(std_marks)

85
